displayName=Transparent Waters
author=Winter Moth
description=Graphical improvements to the bodies of water in Gielinor
tags=water,environment,graphics,sailing
version=0.0.1
plugins=com.transparentwaters.TransparentWatersPlugin
build=standard